[package]
name = "sassers"
description = "A Sass compiler in Rust"
version = "0.2.0-notevenclose"
authors = ["Carol Nichols <carol.nichols@gmail.com>"]
repository = "https://github.com/carols10cents/sassers"
readme = "README.md"
license = "MIT"

[dependencies]
docopt = "0.6.64"